
spring:
  application:
    name: client-service-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
# Actuator
# swagger
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: true
  api-docs:
    enabled: true
    path: /api-docs
# logging
logging:
  level:
    root: INFO
server:
  port: ${CLIENT_PORT:3030}
